course_name = "移动机器人导论"
course_code = "AUTO3012"
notices = ""

[[lecturers]]
name = "李芃"
  [[lecturers.reviews]]
  content = "授课风格：念 PPT。时有一些板书和扩展。"
  [lecturers.reviews.author]
  name = ""
  link = ""
  date = ""

textbooks = []
online_resources = []

[[course]]
content = "课程覆盖感知、规划、控制等多方面内容，比较基础。"
[course.author]
name = "Oliver Wu"
link = "https://www.github.com/OliverWu515"
date = "2024-11-01"

[[exam]]
content = "没有考试。"
[exam.author]
name = "Oliver Wu"
link = "https://www.github.com/OliverWu515"
date = "2024-11-01"

[[advice]]
content = """PPT 观感不佳，稍显混乱，可听老师讲解。概念比较多，但最后不考试，无需死记硬背。

实验有四个，是一天做完（1-8 节），需当堂验收。
前两个是仿真，内容分别是纯跟踪算法路径跟踪以及 Dijkstra、A* 算法路径搜索，需要写 MATLAB 程序，繁而不难（吐槽一下有错的示例代码）；
后两个是用实验室的机器人进行建图和导航，无需写代码，比较简单。建议大家去干扰较少的楼道或电梯间里完成实验。"""
[advice.author]
name = "Oliver Wu"
link = "https://www.github.com/OliverWu515"
date = "2024-11-01"

schedule = []
related_links = []

[[misc]]
content = "成绩构成：作业20%, 实验40%, 实验报告40%"
[misc.author]
name = ""
link = ""
date = ""